name: nlp_study
dependencies:
  - python=3.10
  - jupyter_contrib_nbextensions
  - pip:
      - torch>=1.2.0
      - gensim>=3.7.0
      - sklearn 
      - seaborn
      - tqdm 
      - nltk 
      - lazyme 
      - requests
